repos:
  - repo: local
    hooks:
    - id: unittest
      name: Unit tests
      entry: python -m unittest
      language: system
      always_run: true
      exclude: '.'  # don't pass filepaths to unittest
